trigger:
  - main
variables:
  vmImage: "ubuntu-latest"
  serviceConnection: "HDFC-Manual"
  resourceGroup: "backend-resource-group"
  storageAccount: "backendstorageaccount123"
  containerName: "backend-container"

stages:

  - stage: Terraform
    displayName: Terraform Infra Creation

    jobs:

      - job: Terraform_Dev
        displayName: Terraform Dev
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: Terraform Init Dev
            inputs:
              provider: azurerm
              command: init
              workingDirectory: '$(System.DefaultWorkingDirectory)/Root'
              backendServiceArm: $(serviceConnection)
              backendAzureRmResourceGroupName: $(resourceGroup)
              backendAzureRmStorageAccountName: $(storageAccount)
              backendAzureRmContainerName: $(containerName)
              backendAzureRmKey: 'dev-backend-2002'

          - task: TerraformTask@5
            displayName: Terraform Apply Dev
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: '$(System.DefaultWorkingDirectory)/Root'
              commandOptions: '-var-file="Environments/Dev/dev.tfvars" -auto-approve'
              environmentServiceNameAzureRM: $(serviceConnection)


      - job: Terraform_QA
        displayName: Terraform QA
        dependsOn: Terraform_Dev

        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: Terraform Init QA
            inputs:
              provider: azurerm
              command: init
              workingDirectory: '$(System.DefaultWorkingDirectory)/Root'
              backendServiceArm: $(serviceConnection)
              backendAzureRmResourceGroupName: $(resourceGroup)
              backendAzureRmStorageAccountName: $(storageAccount)
              backendAzureRmContainerName: $(containerName)
              backendAzureRmKey: 'qa-backend-2002'
              commandOptions: '-reconfigure'

          - task: TerraformTask@5
            displayName: Terraform Apply QA
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: '$(System.DefaultWorkingDirectory)/Root'
              commandOptions: '-var-file="Environments/Qa/qa.tfvars" -auto-approve'
              environmentServiceNameAzureRM: $(serviceConnection)


      - job: Terraform_Prod
        displayName: Terraform Prod
        dependsOn: Terraform_QA

        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: Terraform Init Prod
            inputs:
              provider: azurerm
              command: init
              workingDirectory: '$(System.DefaultWorkingDirectory)/Root'
              backendServiceArm: $(serviceConnection)
              backendAzureRmResourceGroupName: $(resourceGroup)
              backendAzureRmStorageAccountName: $(storageAccount)
              backendAzureRmContainerName: $(containerName)
              backendAzureRmKey: 'prod-backend-2002'
              commandOptions: '-reconfigure'

          - task: TerraformTask@5
            displayName: Terraform Apply Prod
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: '$(System.DefaultWorkingDirectory)/Root'
              commandOptions: '-var-file="Environments/Prod/prod.tfvars" -auto-approve'
              environmentServiceNameAzureRM: $(serviceConnection)

  - stage: SonarQube
    displayName: SonarQube Analysis
    dependsOn: Terraform
    
    jobs:
      - job: SonarQube

        steps:
          - checkout: self
          - task: SonarQubePrepare@8
            inputs:
              SonarQube: 'sonarqube'
              scannerMode: 'cli'
              configMode: 'manual'
              cliProjectKey: 'Java-Azure-Web-App'
              cliProjectName: 'Java Azure Web App'
              cliSources: '.'

          - task: Maven@4
            inputs:
              azureSubscription: $(serviceConnection)
              mavenPomFile: 'java-azure-webapp-cicd/pom.xml'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: true
              sqMavenPluginVersionChoice: 'latest'
          - task: SonarQubePublish@8
            inputs:
              pollingTimeoutSec: '300'

          

        
