trigger:
  - main
variables:
  
  vmImage: "ubuntu-latest"
  serviceConnection: "HDFC-Manual"
  resourceGroup: "backend-resource-group"
  storageAccount: "backendstorageaccount123"
  containerName: "backend-container"
  acrServiceConnection: "acrServiceConnection"
  imageName: javaapp
  dockerfilePath: java-azure-webapp-cicd/Dockerfile
  imageTag: $(Build.BuildId)
  acrLoginServer: acrregistry123.azurecr.io

stages:

#==========================Terraform infra dev,qa,prod=======================================

  - stage: Terraform
    displayName: Terraform Infra Creation

    jobs:

      - job: Terraform_Dev
        displayName: Terraform Dev
        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: Terraform Init Dev
            inputs:
              provider: azurerm
              command: init
              workingDirectory: '$(System.DefaultWorkingDirectory)/Root'
              backendServiceArm: $(serviceConnection)
              backendAzureRmResourceGroupName: $(resourceGroup)
              backendAzureRmStorageAccountName: $(storageAccount)
              backendAzureRmContainerName: $(containerName)
              backendAzureRmKey: 'dev-backend-2002'

          - task: TerraformTask@5
            displayName: Terraform Apply Dev
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: '$(System.DefaultWorkingDirectory)/Root'
              commandOptions: '-var-file="Environments/Dev/dev.tfvars" -auto-approve'
              environmentServiceNameAzureRM: $(serviceConnection)


      - job: Terraform_QA
        displayName: Terraform QA
        dependsOn: Terraform_Dev

        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: Terraform Init QA
            inputs:
              provider: azurerm
              command: init
              workingDirectory: '$(System.DefaultWorkingDirectory)/Root'
              backendServiceArm: $(serviceConnection)
              backendAzureRmResourceGroupName: $(resourceGroup)
              backendAzureRmStorageAccountName: $(storageAccount)
              backendAzureRmContainerName: $(containerName)
              backendAzureRmKey: 'qa-backend-2002'
              commandOptions: '-reconfigure'

          - task: TerraformTask@5
            displayName: Terraform Apply QA
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: '$(System.DefaultWorkingDirectory)/Root'
              commandOptions: '-var-file="Environments/Qa/qa.tfvars" -auto-approve'
              environmentServiceNameAzureRM: $(serviceConnection)


      - job: Terraform_Prod
        displayName: Terraform Prod
        dependsOn: Terraform_QA

        steps:
          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: 'latest'

          - task: TerraformTask@5
            displayName: Terraform Init Prod
            inputs:
              provider: azurerm
              command: init
              workingDirectory: '$(System.DefaultWorkingDirectory)/Root'
              backendServiceArm: $(serviceConnection)
              backendAzureRmResourceGroupName: $(resourceGroup)
              backendAzureRmStorageAccountName: $(storageAccount)
              backendAzureRmContainerName: $(containerName)
              backendAzureRmKey: 'prod-backend-2002'
              commandOptions: '-reconfigure'

          - task: TerraformTask@5
            displayName: Terraform Apply Prod
            inputs:
              provider: azurerm
              command: apply
              workingDirectory: '$(System.DefaultWorkingDirectory)/Root'
              commandOptions: '-var-file="Environments/Prod/prod.tfvars" -auto-approve'
              environmentServiceNameAzureRM: $(serviceConnection)

  #===============================Sonar Qube=========================================

  # - stage: SonarQube
  #   displayName: SonarQube Analysis
  #   dependsOn: Terraform
    
  #   jobs:
  #     - job: SonarQube

  #       steps:
  #         - checkout: self


  #         - task: JavaToolInstaller@1
  #           displayName: "Use Java 21"
  #           inputs:
  #             versionSpec: "21"
  #             jdkArchitectureOption: "x64"
  #             jdkSourceOption: "PreInstalled"

  #         - script: |
  #             java -version
  #             javac -version
  #             mvn -version
  #           displayName: "Check Java and Maven Version"
              
  #         - task: SonarQubePrepare@8
  #           inputs:
  #             SonarQube: 'sonarqube'
  #             scannerMode: 'cli'
  #             configMode: 'manual'
  #             cliProjectKey: 'Java-Azure-Web-App'
  #             cliProjectName: 'Java Azure Web App'
  #             cliSources: '.'
  #         - script: |
  #             cd "$(System.DefaultWorkingDirectory)/java-azure-webapp-cicd"
  #             chmod +x mvnw
  #             ./mvnw clean compile sonar:sonar
  #           displayName: "Run SonarQube Analysis"
          

  #         - task: Maven@4
  #           inputs:
  #             azureSubscription: $(serviceConnection)
  #             mavenPomFile: 'java-azure-webapp-cicd/pom.xml'
  #             options: '-Dsonar.branch.name='
  #             publishJUnitResults: true
  #             testResultsFiles: '**/surefire-reports/TEST-*.xml'
  #             javaHomeOption: 'JDKVersion'
  #             mavenVersionOption: 'Default'
  #             mavenAuthenticateFeed: false
  #             effectivePomSkip: false
  #             sonarQubeRunAnalysis: true
  #             sqMavenPluginVersionChoice: 'latest'

          

  #         - task: SonarQubePublish@8
  #           inputs:
  #             pollingTimeoutSec: '300'

  # #=======================Docker Build and Push to ACR ===========================================

          



  - stage: Docker
    dependsOn: Terraform
    displayName: Docker Build and Push
    jobs:
      - job: DockerBuildandPush
      
        steps:
          - checkout: self
          - task: Docker@2
            inputs:
              containerRegistry: $(acrServiceConnection)
              repository: $(imageName)
              command: 'buildAndPush'
              Dockerfile: $(dockerfilePath)
              tags: |
                $(imageTag)
                latest


  - stage: Deploy_Dev
    displayName: Deploy to Dev web app
    dependsOn: Docker

    jobs:
      - job: DeployToDevWebApp
        steps:
          - checkout: self

          - task: AzureRmWebAppDeployment@5
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'HDFC-Manual'
              appType: 'webAppContainer'
              WebAppName: 'Dev-linux-web-app'
              DockerNamespace: $(acrLoginServer)
              DockerRepository: javaapp
              DockerImageTag: $(imageTag)

  - stage: Deploy_Qa
    displayName: Deploy to Qa web app
    dependsOn: Deploy_Dev

    jobs:
      - job: DeployToQaWebApp
        steps:
          - checkout: self

          - task: AzureRmWebAppDeployment@5
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'HDFC-Manual'
              appType: 'webAppContainer'
              WebAppName: 'Qa-linux-web-app'
              DockerNamespace: $(acrLoginServer)
              DockerRepository: javaapp
              DockerImageTag: $(imageTag)
 
  - stage: Deploy_Prod
    displayName: Deploy to Prod web app
    dependsOn: Deploy_Qa

    jobs:
      - job: DeployToProdWebApp
        steps:
          - checkout: self

          - task: AzureRmWebAppDeployment@5
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'HDFC-Manual'
              appType: 'webAppContainer'
              WebAppName: 'Prod-linux-web-app'
              DockerNamespace: $(acrLoginServer)
              DockerRepository: javaapp
              DockerImageTag: $(imageTag)


                          
                                
                              
                          

